# Generated by Django 5.0.3 on 2024-03-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('power', models.DecimalField(decimal_places=3, max_digits=20)),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
    ]
